#ifndef DEVICEHANDLER_GLOBAL_H
#define DEVICEHANDLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DEVICEHANDLER_LIBRARY)
#define DECLARE_LIB DEVICEHANDLERSHARED_EXPORT
#  define DEVICEHANDLERSHARED_EXPORT Q_DECL_EXPORT
#else
#define DECLARE_LIB
#  define DEVICEHANDLERSHARED_EXPORT Q_DECL_IMPORT
#endif


#endif // DEVICEHANDLER_GLOBAL_H
