#ifndef CIRCLEDETECTORPLUGINLOADERVIEW_GLOBAL_H
#define CIRCLEDETECTORPLUGINLOADERVIEW_GLOBAL_H

#ifndef CIRCLE_PLUGIN_LOADER_USE_STATIC_LIB
#   include <QtCore/qglobal.h>
#   define CIRCLE_PLUGIN_LOADER_LIB CIRCLEPLUGINLOADERSHARED_EXPORT
#   if defined(CIRCLEDETECTORVIEW_LIBRARY)
#       define CIRCLEPLUGINLOADERSHARED_EXPORT Q_DECL_EXPORT
#   else
#       define CIRCLEPLUGINLOADERSHARED_EXPORT Q_DECL_IMPORT
#   endif
#else
#   define CIRCLE_PLUGIN_LOADER_LIB
#endif

#define CIRCLE_PLUGIN_LOADER_BEGIN_NAMESPACE
#define CIRCLE_PLUGIN_LOADER_END_NAMESPACE

#ifdef USE_CPP_STD_14
#include <cstdio>
#   define INIT_UNIQUE_PTR(TYPE, ...) std::make_unique<TYPE>(__VA_ARGS__)
#else
#   define INIT_UNIQUE_PTR(TYPE, ...) std::unique_ptr<TYPE>(new TYPE(__VA_ARGS__))
#endif
#endif // CIRCLEDETECTORPLUGINMODEL_GLOBAL_H
