#ifndef CVVIDEOCAPTURELIB_H
#define CVVIDEOCAPTURELIB_H

#include <QtCore/qglobal.h>

#if defined(CVVIDEOCAPTURE_LIBRARY)
#  define CVVIDEOCAPTURESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CVVIDEOCAPTURESHARED_EXPORT Q_DECL_IMPORT
#endif


#endif // CVVIDEOCAPTURELIB_H
