#ifndef SERIALPORTMODEL_GLOBAL_H
#define SERIALPORTMODEL_GLOBAL_H

#ifdef SERIAL_MODEL_USE_SHARED_LIB
#include <QtCore/qglobal.h>
#   if defined(SERIALPORTMODEL_LIBRARY)
#       define SERIALPORTMODELSHARED_EXPORT Q_DECL_EXPORT
#   else
#       define SERIALPORTMODELSHARED_EXPORT Q_DECL_IMPORT
#   endif
#else
#   define SERIALPORTMODELSHARED_EXPORT
#endif
#endif // SERIALPORTMODEL_GLOBAL_H
