#ifndef IMAGEPROCESSORS_GLOBAL_H
#define IMAGEPROCESSORS_GLOBAL_H

#ifdef USE_SHARED_LIB
#include <QtCore/qglobal.h>
#define IMG_PROC_LIB IMAGEPROCESSORSSHARED_EXPORT
#if defined(IMAGEPROCESSORS_LIBRARY) 
#  define IMAGEPROCESSORSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IMAGEPROCESSORSSHARED_EXPORT Q_DECL_IMPORT
#endif
#else
#define IMG_PROC_LIB
#endif // IMAGEPROCESSORS_GLOBAL_H
#endif
