#ifndef IMAGEPROCESSORS_GLOBAL_H
#define IMAGEPROCESSORS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IMAGEPROCESSORS_LIBRARY)
#  define IMAGEPROCESSORSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IMAGEPROCESSORSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGEPROCESSORS_GLOBAL_H
